import{S as p,i as l}from"./assets/vendor-46aac873.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const u=document.querySelector(".form-seach"),c=document.querySelector(".gallery-images"),a=document.querySelector(".loader");u.addEventListener("submit",d);a.style.display="none";function m(o){if(!o.ok)throw new Error(o.status);return o.json()}function f(o){const n="https://pixabay.com/api",r="41909271-8b5dab2225a1cd5a9757159a5",s=new URLSearchParams({key:r,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"9"}),e=`${n}/?${s}`;return fetch(e).then(m)}const y=new p(".gallery-images a",{captionDelay:250});function d(o){o.preventDefault(),a.style.display="inline-block",c.innerHTML="";const n=o.currentTarget,r=n.elements.query.value;if(!r){a.style.display="none",l.show({title:"❌",messageColor:"white",message:"Sorry, there are no images matching your search query.Please try again!",position:"topRight",color:"red"}),a.style.display="none";return}console.log(r),f(r).then(s=>{const e=s.hits;if(!s.total){a.style.display="none",l.show({title:"❌",messageColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"});return}let t="";for(const i of e)t+=h(i);a.style.display="none",c.innerHTML=t,y.refresh(),console.log(t)}).catch(s=>console.log(s)).finally(()=>{n.reset()})}function h({webformatURL:o,largeImageURL:n,tags:r,likes:s,views:e,comments:t,downloads:i}){return`<li class = "list-item">
    <a href="${n}" ><img class="search-image" src = "${o}" alt = "${r}" ><div class="options">
    <p class="options-item"> likes:<span class="options-item-span">${s}</span></p>
    <p class="options-item"> views:<span class="options-item-span">${e}</span></p>
    <p class="options-item"> comments:<span class="options-item-span">${t}</span></p>
    <p class="options-item"> downloads:<span class="options-item-span">${i}</span></p></div>
  
    </a>
    
    </li>`}
//# sourceMappingURL=commonHelpers.js.map
