import{S as p,i}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const u=document.querySelector(".form-seach"),l=document.querySelector(".gallery-images"),c=document.querySelector(".loader");u.addEventListener("submit",d);function m(o){if(!o.ok)throw new Error(o.status);return o.json()}new URLSearchParams({key:API_KEY,q:value,image_type:"photo",orientation:"horizontal",safesearch:"true"});function f(o){const r="https://pixabay.com/api",n=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}),s="41909271-8b5dab2225a1cd5a9757159a5",e=`${r}/?${n}`;return fetch(e).then(m)}const h=new p(".gallery-images a",{captionDelay:250});function d(o){o.preventDefault(),c.style.display="block",l.innerHTML="";const r=o.currentTarget,n=r.elements.query.value;if(!n){i.show({title:"❌",messageColor:"white",message:"Sorry, there are no images matching your search query.Please try again!",position:"topRight",color:"red"}),c.style.display="none";return}console.log(n),f(n).then(s=>{const e=s.hits;if(!s.total){i.show({title:"❌",messageColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"});return}let t="";for(const a of e)t+=y(a);l.innerHTML=t,h.refresh(),console.log(t)}).catch(s=>console.log(s)).finally(()=>{r.reset()})}function y({webformatURL:o,largeImageURL:r,tags:n,likes:s,views:e,comments:t,downloads:a}){return`<li class = "list-item">
    <a href="${r}" ><img class="search-image" src = "${o}" alt = "${n}" ><div class="options">
    <p class="options-item"> likes:<span class="options-item-span">${s}</span></p>
    <p class="options-item"> views:<span class="options-item-span">${e}</span></p>
    <p class="options-item"> comments:<span class="options-item-span">${t}</span></p>
    <p class="options-item"> downloads:<span class="options-item-span">${a}</span></p></div>
  
    </a>
    
    </li>`}
//# sourceMappingURL=commonHelpers.js.map
